spring:
  profiles:
    active: dev
  #配置数据库
  datasource:
    name: db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis.xml
  type-aliases-package: com.zzax.mall.domain
#配置logback
logging:
  config: classpath:config/logback-spring.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql