spring:
  application:
    name: mall
  profiles:
    active: dev
  #配置数据库
  datasource:
    name: db
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis.xml
  type-aliases-package: com.zzax.mall.domain
#配置logback
logging:
  config: classpath:config/logback-spring.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql